### ISSUE TITLE
Denie a goal, card, repair robot

### ISSUE THREAD

**Issue by StefanNiemczyk** [RoboCup-MSL/RefBox2015#3]
Hallo,

I have tested the refbox and found a bug. If a goal is given a goal message is send instantly. If the goal is denied by pressing the button again (before pressing start) no message is send. The next send command message contains some strange characters. 

There is a similar behaviour for cards and repair. A message is send if the button is pressed. If the button is pressed again, no denying message is send. In this situation, the refbox does not show that a card was given/a robot was send out for repair, but a message was send to the client already.

Regards,
Stefan (Carpe Noctem Cassel)

**Comment by ricdays** [comment]
Thanks for the feedback!
This issue is now fixed on 2b2d345

Since Goal+ and Goal- have commands for each, this is now sent instantly upon clicking the button.
The rest of the situations (Red Card, Yellow Card, Double Yellow Card, Repair) remain "on-hold" until there is a new START. This means that while you can award a card and undo, nothing is sent. The final decision is communicated on the next game state change (when the assistant referee can no longer undo anyway).
