### ISSUE TITLE
Refbox JSON message lacks a header

### ISSUE THREAD

**Issue by kmeessen** [RoboCup-MSL/RefBox2015#50]
The new JSON format for the refbox messages is based on sending plain JSON strings over a socket which makes a robust client implementation cumbersome. Adding a simple header would make the message parsing much easier and robust. The minimum information that the header contains should be the size of the payload of the message.

**Comment by BernardoCunha** [comment]
To simplify the client implementation, the simple solution that was used in the current protocol is to add a nul char ('\0') to the end of every message. Since '\0' don not ever happen within a JSON message, detection of this nul char determines the end of a message and, therefore, the beginning of the next one.
